[package]
name = "sya_sys"
authors = [ "Samuel Nösslböck <samuel.noesslboeck@gmail.com>" ]
version = "0.1.0"
edition = "2021"

[dependencies]
syact = { path = "../../../libs/syact", features = [ "rasp" ] }
sybot = { path = "../../../libs/sybot", features = [ "rasp" ] }